// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA9wW9eADAZ2EVTvlI12rijtfLzA7HOsfk',
//     appId: '1:456171594984:web:e677a16d45d65c5920955d',
//     messagingSenderId: '456171594984',
//     projectId: 'udemycourse-35586',
//     authDomain: 'udemycourse-35586.firebaseapp.com',
//     storageBucket: 'udemycourse-35586.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBv1IniHmUeWVxLq8uKUv6oFG3k5uwFx2k',
//     appId: '1:456171594984:android:51eaea19008a9a7220955d',
//     messagingSenderId: '456171594984',
//     projectId: 'udemycourse-35586',
//     storageBucket: 'udemycourse-35586.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAIKbx5xcTRjB_8tfws-iCgvq2x2nj3nCU',
//     appId: '1:456171594984:ios:aefe3534e2376a2720955d',
//     messagingSenderId: '456171594984',
//     projectId: 'udemycourse-35586',
//     storageBucket: 'udemycourse-35586.appspot.com',
//     iosBundleId: 'com.example.udemycourse',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAIKbx5xcTRjB_8tfws-iCgvq2x2nj3nCU',
//     appId: '1:456171594984:ios:7b848bc98ccbe76220955d',
//     messagingSenderId: '456171594984',
//     projectId: 'udemycourse-35586',
//     storageBucket: 'udemycourse-35586.appspot.com',
//     iosBundleId: 'com.example.udemycourse.RunnerTests',
//   );
// }
